[package]
name = "dyndnsd"
version = "0.2.0"
authors = ["Carsten Saathoff <carsten@kodemaniak.de>"]
edition = "2018"

[dependencies]
futures = "0.3.18"
tokio = { version = "1.14.0", features = [ "rt", "macros" ] }
async-trait = "0.1.51"
clokwerk = "0.3.5"
serde = "1.0.126"
serde_json = "1.0.69"
surf = { version = "2.3.2", features = [ "h1-client-rustls" ] }
mockall_double = "0.2.0"
envconfig = "0.10.0"
env_logger = "0.9.0"
log = "0.4.14"
openssl-probe = "0.1.4"

[dev-dependencies]
mockall = "0.10.1"
wiremock = "0.5.8"

