[package]
name = "dyndnsd"
version = "0.1.0"
authors = ["Carsten Saathoff <carsten@kodemaniak.de>"]
edition = "2018"

[dependencies]
futures = "0.3.15"
tokio = { version = "1.8.1", features = [ "full" ] }
async-trait = "0.1.50"
pnet = "0.28.0"
clokwerk = "0.3.5"
serde = "1.0.126"
serde_json = "1.0.64"
surf = "2.2.0"
mockall_double = "0.2.0"
openssl = { version = "0.10", features = ["vendored"] }
envconfig = "0.10.0"

[dev-dependencies]
mockall = "0.10.1"
wiremock = "0.5.4"
