apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dyndnsd.fullname" . }}
  labels:
    {{- include "dyndnsd.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "dyndnsd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "dyndnsd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dyndnsd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Define the environment variable
            - name: DYNDNSD_POLL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.environmentVars }}
                  key: DYNDNSD_POLL_INTERVAL
            - name: DYNDNSD_POLL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.environmentVars }}
                  key: DYNDNSD_SUBDOMAIN
            - name: DYNDNSD_POLL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.environmentVars }}
                  key: DYNDNSD_UBUS_URL
            - name: DYNDNSD_POLL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.environmentVars }}
                  key: DYNDNSD_UBUS_USER
            - name: DYNDNSD_POLL_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.environmentVars }}
                  key: DYNDNSD_DOMAIN
            - name: DYNDNSD_HETZNER_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretVars }}
                  key: DYNDNSD_HETZNER_API_TOKEN
            - name: DYNDNSD_UBUS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretVars }}
                  key: DYNDNSD_UBUS_SECRET
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
